// stickers.js
const stickers = [
  "cat_1.png", "cat_2.png", "cat_3.png", "cat_4.png",
  "heart_1.png", "heart_2.png",
  "rabbit_1.png", "rabbit_2.png", "cat_5.png", "cat_6.png",
  "AdorableBabyBearHoldingAHeartShapedBalloonPastelColorsKawaiiStyleOutlinedForStickerSoftShadows1.png",
  "AdorableBabyBearHoldingAHeartShapedBalloonPastelColorsKawaiiStyleOutlinedForStickerSoftShadows2.png",
  "HappyBubbleTeaWithSmilingFaceAndSparklesPastelPinkAndMintBackgroundStickerStyle1.png",
  "HappyBubbleTeaWithSmilingFaceAndSparklesPastelPinkAndMintBackgroundStickerStyle2.png",
  "ChibiCatWearingATinyHoodieSittingOnACloudRainbowSparklesAroundKawaiiStickerDesign1.png",
  "ChibiCatWearingATinyHoodieSittingOnACloudRainbowSparklesAroundKawaiiStickerDesign2.png",
  "CuteCorgiWithTinyAngelWingsAndHaloDreamyAestheticWhiteStickerBorder1.png",
  "CuteCorgiWithTinyAngelWingsAndHaloDreamyAestheticWhiteStickerBorder2.png",
  "SmilingSunHuggingALittleCloudPastelAestheticOutlinedStickerStyle1.png",
  "SmilingSunHuggingALittleCloudPastelAestheticOutlinedStickerStyle2.png",
  "MinimalistCuteFrogSittingOnALilyPadPastelGreenTonesCleanWhiteBorderAestheticSticker1.png",
  "MinimalistCuteFrogSittingOnALilyPadPastelGreenTonesCleanWhiteBorderAestheticSticker2.png",
  "SweetStrawberryMilkCartonWithHappyFaceKawaiiAestheticPinkAndWhiteTonesStickerArt1.png",
  "SweetStrawberryMilkCartonWithHappyFaceKawaiiAestheticPinkAndWhiteTonesStickerArt2.png",
  "CuteAIRobotWithHeartEyesAndPastelBlueAccentsFriendlyVibeSimpleStickerStyle1.png",
  "CuteAIRobotWithHeartEyesAndPastelBlueAccentsFriendlyVibeSimpleStickerStyle2.png",
  "KawaiiBunnyWithTinyHeadphonesListeningToMusicPastelBackgroundStickerOutline1.png",
  "KawaiiBunnyWithTinyHeadphonesListeningToMusicPastelBackgroundStickerOutline2.png",
  "AdorableToastWithButterSmileSimpleLineArtCozyPastelPalette1.png",
  "AdorableToastWithButterSmileSimpleLineArtCozyPastelPalette2.png"
];
